# Generated by Django 5.1.1 on 2024-09-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product', 'version_number', 'version_name'), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Версия активна?', null=True, verbose_name='Признак текущей версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(blank=True, help_text='Введите наименование версии продукта', max_length=150, null=True, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, default='0', help_text='Введите номер версии продукта', null=True, verbose_name='Номер версии'),
        ),
    ]
